[env]
DATABASE_URL = { relative = false, value = "sqlite:///home/lukas/code/repos/diagware-rs/src/database.db" }

# [build]
# target = "aarch64-unknown-linux-gnu"
# target = "x86_64-unknown-linux-gnu"
# linker = "aarch64-linux-gnu-gcc"
