name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  # DATABASE_URL: "sqlite:///home/lukas/code/repos/diagware/src/database.db"
  DATABASE_URL: "sqlite://src/database.db"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
